CREATE DATABASE GLEARNING;

USE GLEARNING;

/*TABELA DE ROUPAS*/
CREATE TABLE TB_ROUPA(
	
	ROUPA_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ROUPA_NOME VARCHAR(50) NOT NULL,
	ROUPA_PRECO DOUBLE NOT NULL,
	ROUPA_NOMEID VARCHAR(50) NOT NULL

)ENGINE=INNODB;

/*TABELA DE ACESSORIOS*/
CREATE TABLE TB_ACESSORIO(
	
	ACESSORIO_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ACESSORIO_NOME VARCHAR(50) NOT NULL,
	ACESSORIO_PRECO DOUBLE NOT NULL,
	ACESSORIO_NOMEID VARCHAR(50) NOT NULL

)ENGINE=INNODB;

/*TABELA DE USUARIOS ADMNINS*/
CREATE TABLE TB_USER_ADM (	

	USER_ADM_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ADM_CPF VARCHAR(11) NOT NULL,
	USER_ADM_NOME VARCHAR(50) NOT NULL,
	USER_ADM_LOGIN VARCHAR(50) NOT NULL,
	USER_ADM_SENHA VARCHAR(50) NOT NULL,
	USER_ADM_EMAIL VARCHAR(50) NOT NULL

)ENGINE=INNODB;

/*TABELA DE USUARIOS PROFESSORES*/
CREATE TABLE TB_USER_PROFESSOR (

	USER_PROFESSOR_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_PROFESSOR_CPF VARCHAR(11) NOT NULL,
	USER_PROFESSOR_NOME VARCHAR(50) NOT NULL,
	USER_PROFESSOR_LOGIN VARCHAR(50) NOT NULL,
	USER_PROFESSOR_SENHA VARCHAR(50) NOT NULL,
	USER_PROFESSOR_EMAIL VARCHAR(50) NOT NULL

)ENGINE=INNODB;

/*TABELA DE USUARIOS MONITORES*/
CREATE TABLE TB_USER_MONITOR (

	USER_MONITOR_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_MONITOR_CPF VARCHAR(11) NOT NULL,
	USER_MONITOR_NOME VARCHAR(50) NOT NULL,
	USER_MONITOR_LOGIN VARCHAR(50) NOT NULL,
	USER_MONITOR_SENHA VARCHAR(50) NOT NULL,
	USER_MONITOR_EMAIL VARCHAR(50) NOT NULL

)ENGINE=INNODB;

/*TABELA DE USUARIOS ESTUDANTES*/
CREATE TABLE TB_USER_ESTUDANTE (

	USER_ESTUDANTE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ESTUDANTE_CPF VARCHAR(11) NOT NULL,
	USER_ESTUDANTE_NOME VARCHAR(50) NOT NULL,
	USER_ESTUDANTE_LOGIN VARCHAR(50) NOT NULL,
	USER_ESTUDANTE_SENHA VARCHAR(50) NOT NULL,
	USER_ESTUDANTE_EMAIL VARCHAR(50) NOT NULL,
	USER_ESTUDANTE_NIVEL INT NOT NULL,
	USER_ESTUDANTE_PTOTAIS INT NOT NULL,
	USER_ESTUDANTE_PSEMESTRE INT NOT NULL,
	USER_ESTUDANTE_PATUAIS INT NOT NULL,
	COD_ROUPA INT NOT NULL,
	COD_ACESSORIO INT NOT NULL,
	CONSTRAINT FOREIGN KEY (COD_ROUPA) REFERENCES TB_ROUPA(ROUPA_ID),
	CONSTRAINT FOREIGN KEY (COD_ACESSORIO) REFERENCES TB_ACESSORIO(ACESSORIO_ID)

)ENGINE=INNODB;

/*TABELA DE SALAS*/
CREATE TABLE TB_SALA (

	SALA_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SALA_CODIGO VARCHAR(12) NOT NULL,
	SALA_NOME VARCHAR(50) NOT NULL,
	COD_USER_PROFESSOR INT NOT NULL,
	CONSTRAINT FOREIGN KEY (COD_USER_PROFESSOR) REFERENCES TB_USER_PROFESSOR(USER_PROFESSOR_ID)

)ENGINE=INNODB;

/*TABELA DE RELAÇÃO ESTUDANTES E SALAS*/
CREATE TABLE TB_ESTUDANTE_SALA (

	ESTUDANTE_SALA_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	COD_ESTUDANTE INT NOT NULL,
	COD_SALA INT NOT NULL,	
	CONSTRAINT FOREIGN KEY (COD_ESTUDANTE) REFERENCES TB_USER_ESTUDANTE(USER_ESTUDANTE_ID),
	CONSTRAINT FOREIGN KEY (COD_SALA) REFERENCES TB_SALA(SALA_ID)

)ENGINE=INNODB;

/*  ----------- INSERTS ------------- */

INSERT INTO TB_ROUPA(ROUPA_NOME, ROUPA_PRECO, ROUPA_NOMEID) VALUES
('Roupa normal Masculina', 	10, 	'male_1'),
('Roupa normal Feminina', 	10, 	'female_1');

INSERT INTO TB_ACESSORIO(ACESSORIO_NOME, ACESSORIO_PRECO, ACESSORIO_NOMEID) VALUES
('Nada', 		0,	 	'acessory_0'),
('Chapeu', 		10, 	'acessory_1'),
('Gravata', 	10, 	'acessory_2'),
('Flor', 		10, 	'acessory_3');

INSERT INTO TB_USER_ADM(USER_ADM_CPF, USER_ADM_NOME, USER_ADM_LOGIN, USER_ADM_SENHA, USER_ADM_EMAIL) VALUES 
('10000000001', 'ADMINISTRADOR', 'admin', 'admin', 'admin@gmail.com');

INSERT INTO TB_USER_PROFESSOR(USER_PROFESSOR_CPF, USER_PROFESSOR_NOME, USER_PROFESSOR_LOGIN, USER_PROFESSOR_SENHA, USER_PROFESSOR_EMAIL) VALUES 
('20000000001', 'Professor 1', 'professor1', 'professor1', 'professor1@gmail.com'),
('20000000002', 'Professor 2', 'professor2', 'professor2', 'professor2@gmail.com');

INSERT INTO TB_USER_MONITOR(USER_MONITOR_CPF, USER_MONITOR_NOME, USER_MONITOR_LOGIN, USER_MONITOR_SENHA, USER_MONITOR_EMAIL) VALUES 
('30000000001', 'Monitor 1', 'monitor1', 'monitor1', 'monitor1@gmail.com'),
('30000000002', 'Monitor 2', 'monitor2', 'monitor2', 'monitor2@gmail.com');

INSERT INTO TB_USER_ESTUDANTE(USER_ESTUDANTE_CPF, USER_ESTUDANTE_NOME, USER_ESTUDANTE_LOGIN, USER_ESTUDANTE_SENHA, USER_ESTUDANTE_EMAIL, USER_ESTUDANTE_NIVEL, USER_ESTUDANTE_PTOTAIS, USER_ESTUDANTE_PSEMESTRE, USER_ESTUDANTE_PATUAIS, COD_ROUPA, COD_ACESSORIO) VALUES 
('40000000001', 'Aluno 1', 'aluno1', 'aluno1', 'aluno1@gmail.com', 1, 10, 5, 5, 1, 1),
('40000000002', 'Aluno 2', 'aluno2', 'aluno2', 'aluno2@gmail.com', 1, 10, 5, 5, 2, 1),
('40000000003', 'Aluno 3', 'aluno3', 'aluno3', 'aluno3@gmail.com', 1, 10, 5, 5, 2, 1),
('40000000004', 'Aluno 4', 'aluno4', 'aluno4', 'aluno4@gmail.com', 1, 10, 5, 5, 2, 1),
('40000000005', 'Aluno 5', 'aluno5', 'aluno5', 'aluno5@gmail.com', 1, 10, 5, 5, 1, 1),
('40000000006', 'Aluno 6', 'aluno6', 'aluno6', 'aluno6@gmail.com', 1, 10, 5, 5, 1, 1);

INSERT INTO TB_SALA(SALA_CODIGO, SALA_NOME, COD_USER_PROFESSOR) VALUES
('1234', 'SALA 1', 1),
('4321', 'SALA 2', 2);

INSERT INTO TB_ESTUDANTE_SALA(COD_ESTUDANTE, COD_SALA) VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 2),
(5, 2),
(6, 2);